--- #YAML:1.0
name:               Sim-OPTS
version:            0.36.14.3
abstract:           Sim::OPTS manages parametric explorations through the ESP-r building simulation platform and performs multiobjective optimization by block coordinate descent.
author:
    - Gian Luca Brunetti <gianluca.brunetti@polimi.it>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::MoreUtils:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
